=== ternovsky/Planner/src/com/ternovsky/xml/shopping-plan.dtd
<!ELEMENT shoppingPlan (coordinates,totals,shops)>

<!ELEMENT coordinates EMPTY>
<!ATTLIST coordinates
	x	CDATA #REQUIRED
	y	CDATA #REQUIRED
>

<!ELEMENT totals (cost,distance)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT distance (#PCDATA)>

<!ELEMENT shops (shop*)>

<!ELEMENT shop (name?,products)>
<!ATTLIST shop
	id	ID #REQUIRED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT products (product+)>

<!ELEMENT product (#PCDATA)>
<!ATTLIST product
	code	CDATA #REQUIRED
	price	CDATA #IMPLIED
>

=== ternovsky/Planner/src/shopping-plan.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE shoppingPlan SYSTEM "shopping-plan.dtd">
<shoppingPlan>
    <coordinates x="50" y="50"/>
    <totals>
        <cost>399.9</cost>
        <distance>900.0</distance>
    </totals>
    <shops>
        <shop id="No1">
            <name>Food Lion</name>
            <products>
                <product code="sausage">Sausage</product>
                <product code="eggs">Eggs</product>
            </products>
        </shop>
        <shop id="No2">
            <name>Bottom Dollar Food</name>
            <products>
                <product code="spam">Spam</product>
            </products>
        </shop>
    </shops>
</shoppingPlan>
